/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-add_tag_module
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_ADD_TAG_MODULE_API_H
#define INCLUDED_ADD_TAG_MODULE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_add_tag_module_EXPORTS
#define ADD_TAG_MODULE_API __GR_ATTR_EXPORT
#else
#define ADD_TAG_MODULE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_ADD_TAG_MODULE_API_H */
